// -------------------------------------------------- //
// This file is autogenerated by pioasm; do not edit! //
// -------------------------------------------------- //

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// --- //
// pwm //
// --- //

#define pwm_wrap_target 0
#define pwm_wrap 12

static const uint16_t pwm_program_instructions[] = {
            //     .wrap_target
    0x9080, //  0: pull   noblock         side 0     
    0xa027, //  1: mov    x, osr                     
    0x9080, //  2: pull   noblock         side 0     
    0xa027, //  3: mov    x, osr                     
    0x9080, //  4: pull   noblock         side 0     
    0xa027, //  5: mov    x, osr                     
    0x9080, //  6: pull   noblock         side 0     
    0xa027, //  7: mov    x, osr                     
    0xa046, //  8: mov    y, isr                     
    0x00ab, //  9: jmp    x != y, 11                 
    0x180c, // 10: jmp    12              side 1     
    0xa042, // 11: nop                               
    0x0089, // 12: jmp    y--, 9                     
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program pwm_program = {
    .instructions = pwm_program_instructions,
    .length = 13,
    .origin = -1,
};

static inline pio_sm_config pwm_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + pwm_wrap_target, offset + pwm_wrap);
    sm_config_set_sideset(&c, 2, true, false);
    return c;
}

static inline void pwm_program_init(PIO pio, uint sm, uint offset, uint pin) {
   pio_gpio_init(pio, pin);
   pio_sm_set_consecutive_pindirs(pio, sm, pin, 1, true);
   pio_sm_config c = pwm_program_get_default_config(offset);
   sm_config_set_sideset_pins(&c, pin);
   float div = (float)clock_get_hz(clk_sys) / (1000000 * 3);
   sm_config_set_clkdiv(&c, div);
   pio_sm_init(pio, sm, offset, &c);  // sm is left disabled at the end
}

#endif

